- name: installing apache2 on ec2s
  hosts: ec2s
  become: true
  tasks: 
    - name: install apache2
      apt: 
        name: apache2
        state: present
    
    - name: restart apache2
      apache2_module: 
        name: rewrite 
        state: present
      notify:
        - restart apache2
    
    - name: apache2 listen on port 8090
      lineinfile: 
        dest: /etc/apache2/ports.conf 
        regexp: "^Listen 80" 
        line: "Listen 8090" 
        state: present
      notify:
        - restart apache2
  

    - name: create my_default_index.html file
      file:
        path: /var/www/html/my_default_index.html 
        state: touch
      
    
    - name: write in my_defaul_index.html file
      lineinfile:
        path: /var/www/html/my_default_index.html 
        line: "hello, apache is running on port 8090"


    - name: put my_default_index.html file in /etc/apache2/mods-available/dir.conf
      lineinfile:
        path: /etc/apache2/mods-available/dir.conf
        regexp: "DirectoryIndex *"
        line: DirectoryIndex my_default_index.html index.html index.cgi index.pl index.php index.xhtml  index.htm
      notify:
        restart apache2
    
      
  handlers:
    - name: restart apache2
      service: 
        name: apache2 
        state: restarted

#**************************task 2***********************

